11-21晚
 位于分支 master
	修改：     src/main/java/org/xzgtemp/web/UserController.java
	修改：     src/main/webapp/WEB-INF/templates/search.html

一些修改说明:

1-4 只看代码看出来的问题和增加的一个功能，、
5 未解决

1.
初始增加“if (session.getAttribute(KEY_USER) == null)”:
如果session中没有 KEY_USER对应的值，就跳转到登陆界面
如果不加这一条，那么若在未登录就可以访问/search，同时，之后user = null,后面用的时候会出现异常
(比如你不登陆直接访问127.0.0.1：8080/search，然后输个值提交，就会出问题)
在后面所有登陆后的页面跳转开始也应该加这一条

2.
关于保留用户在上一轮选择的搜索条件的实现
model中加入对应的参数，
在html中，我们用if给对应的选择加上默认标签
在GetMapping里，应该在model中加入的是默认值
具体见代码

3.
关于目前代码中html和controller中的一些功能的冲突
对于没有查找到结果的情况：
html中通过for语句的else输出了no book yet
controller这边用if(!books.isEmpty())判断，如果没有则跳到尾部执行
model.put("error","Not found any data by your input.");
这里我把controller里的注释掉了

4.
searchBy增加了一类default
对应的功能是get...byTitleOrAuthor
出于美观考虑把外层的if和内层的的switch合并了
(如果觉得不合并更美观也可以该回来，原来的代码我用注释保留了)

5. ！未解决！！！
search界面输入1出错：
PreparedStatementCallback;
SQL [SELECT * FROM Document WHERE title LIKE "%?%"];
Parameter index out of range (1 > number of parameters, which is 0).;
nested exception is java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).

代码如下：
public List<Document> GetDocumentsbyTitle(String Title){
    String sql = "SELECT * FROM Document WHERE title LIKE \"%?%\" ";
    return jdbctemplate.query(sql,documentRowMapper,Title);
}
手工替换掉"?"在控制台里测试是没有报错的
改变搜索选项后只有searchBy=="default"时没有报错
看了一下区别,猜测：如果直接在参数里写查询语句就没错，如果先定义一个字符串string sql = 查询语句，再在参数里写sql就有错
改成
return jdbctemplate.query("SELECT * FROM Document WHERE title LIKE \"%?%\" ",documentRowMapper,Title);
没能解决问题，

去掉双引号
错误信息变成
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback;
bad SQL grammar [SELECT * FROM Document WHERE title LIKE %?% ];
nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax;
check the manual that corresponds to your MySQL server version for the right syntax to use near '%''%' at line 1